### ISSUE TITLE
UTF-8 not working in env variables

### ISSUE THREAD

**Issue by ghost** [kolypto/j2cli#17]
file content of `testfile`:

```
my variable is {{ VAR }}
```

This is working:
`VAR="full of joy" j2 testfile`
outputs:
`my variable is full of joy`

This is not working:
`VAR="full of ñ" j2 testfile`
outputs:

```
Traceback (most recent call last):
  File "/usr/local/bin/j2", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/j2cli/cli.py", line 124, in main
    sys.argv[1:]
  File "/usr/local/lib/python2.7/dist-packages/j2cli/cli.py", line 114, in render_command
    context
  File "/usr/local/lib/python2.7/dist-packages/j2cli/cli.py", line 54, in render_template
    .render(context) \
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/music/test/j2clitest", line 1, in top-level template code
    saludo: {{ hola }}
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)
```

**Comment by zoobab** [comment]
Here is my fix:

sed -e "s/import\ sys/import\ sys\\nreload(sys)\\nsys.setdefaultencoding('utf-8')/g" /usr/bin/j2

Will make a PR. And will fork the project if it is not fixed within a week.

**Comment by zoobab** [comment]
You can try my fix with pip:

$ pip install https://github.com/zoobab/j2cli/archive/utf8.zip

**Comment by kolypto** [comment]
Fixed in the new release

**Comment by zoobab** [comment]
Still the same issue with the release j2cli-0.3.4.post0 .

Can you triple check and reopen the bug if you can reproduce it?

$ pip install https://github.com/kolypto/j2cli/archive/v0.3.4.tar.gz
$ vim mytemplate.j2
hello {{myfriend}}
$ export myfriend=jürgen
$ j2 mytemplate.j2
Traceback (most recent call last):
  File "/usr/bin/j2", line 11, in <module>
    load_entry_point('j2cli==0.3.4.post0', 'console_scripts', 'j2')()
  File "/usr/lib/python2.7/site-packages/j2cli/cli.py", line 170, in main
    sys.argv[1:]
  File "/usr/lib/python2.7/site-packages/j2cli/cli.py", line 150, in render_command
    result = renderer.render(args.template, context)
  File "/usr/lib/python2.7/site-packages/j2cli/cli.py", line 74, in render
    .render(context) \
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/tmpl.j2", line 1, in top-level template code
    hello {{myfriend}}
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

**Comment by kolypto** [comment]
@zoobab, you're right: the issue remains, and unit tests did not reveal it.
